#!/bin/sh
xset +fp ~/.fonts
xset fp rehash
xrdb -merge ~/.Xresources
hsetroot -fill ~/pics/yosemite.jpg -blur 90 &
compton --config ~/.config/compton.conf &
sxhkd &
gm &
#exec ratpoison
#exec howm
wew | focus_watcher.sh &
exec urxvt -g 68X20+401+237
