#! /bin/bash

## script is from https://github.com/CarloBarraco/getweather
## I wrote this to clean up the output
## change location as needed
## weather icons are from lemon fonts
## 2015 dkeg

## get the weather and format nicely
## use an underscore with 2 word cities (New_York_City)
loc='where do you live?'
sky=$(weather -l $loc -d)
temp=$(weather -l $loc -t -i|cut -d ':' -f2|cut -d '.' -f1)"F"
wind=$(weather -l $loc -w -i |cut -d ':' -f2|cut -d '.' -f1)"mph"
sep="  "

case $sky in
    "Sky is clear")
        glyph="⯇ " ;;
    "Overcast clouds")
        glyph="⯄ " ;;
    "Light rain")
        glyph="⮿ " ;;
    "Moderate rain")
        glyph="⯃ " ;;
    "Light snow")
        glyph="⯁ " ;;
    "Snow")
        glyph="⯁ " ;;
esac

echo $glyph $sky$sep $temp$sep⯈ $wind
