#!/bin/bash
BLACK=#FF525252
RED=#FFD86F6B
GREEN=#FFBACD8F
YELLOW=#FFF3D1A7
BLUE=#FF617C83
MAGENTA=#FF9F9CA9
CYAN=#FF88AABB
WHITE=#FFD2D1D4
DARK=#FF0C0C0C
GREY=#FF7C7B78

function statusbar {

	bat() {
	bat0=$(acpi|cut -d "," -f 2)
	echo $bat0
	}
	
	clock() {
	time=$(date "+%A %b %d %R")
	echo $time
	}

	vol() {
	vol="$(amixer get Master | sed -nr '$ s:.*\[(.+%)].*:\1:p')"
	echo $vol
	}

	kern() {
	kern=$(uname -rms)
	echo $kern
	}

	up() {
	up=$(uptime -p)
	echo $up
	}

	cur() {
	cur=$(mpc current)
	test -n "$cur" && echo $cur || echo "you haz no music going"    
	}

	echo "%{F$RED}LinuxBBQ BORK!  %{B-}%{F-} %{F$BLUE}$(cur) %{r}%{F$WHITE}  %{B-}%{F-} %{F$WHITE}$(vol)% %{F$BLUE}  %{B-}%{F-} %{F$BLUE}$(bat)% %{F$YELLOW}  %{B-}%{F-} %{F$YELLOW}%$(clock) "
}
 while true 
 do
	 echo "$(statusbar)"
	sleep 0.5	
 done | bar -g 1280x20 -f "-artwiz-lime-medium-r-normal--10-110-75-75-m-50-iso8859-1, -misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1" -B "#FF0C0C0C" -F "#FFD2C5BC" -p -d &

