#!/bin/bash

# SETTINGS
FONT="-shdw-candy-*-*-*--11-*-*-*-*-*-*-*"
RES="1366x14"
BG="#080608"
FG="#E8EAEC"
BLK="#525252"
RED="#BF606B"
GRN="#BBBB87"
YLW="#876F6A"
BLU="#606B6F"
MAG="#908C9C"
CYN="#88959A"

function statusbar {
function desk() {
CUR=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')
case $CUR in
	0) echo "%{F$RED}%{R}  %{R}%{F-}%{F$BG}  %{F-}%{F$BG}  %{F-}";;
	1) echo "%{F$BG}  %{F-}%{F$RED}%{R}  %{R}%{F-}%{F$BG}  %{F-}";;
	2) echo "%{F$BG}  %{F-}%{F$BG}  %{F-}%{F$RED}%{R}  %{R}%{F-}";;
	*) echo ""
esac
}

function music() {
mus=$(mpc -f %artist% current)
song=$(mpc -f %title% current)
if [[ $mus ]]; then
echo %{F$BLU}%{R}  %{R} $mus %{F$YLW}$song%{F-}
else
echo %{F$BLK}%{R}  %{R}%{F-}
fi
}

function temperature() {
temp=$(sensors | grep "Physical id 0" | cut -d'+' -f2 | head -c2)
if [[ $temp < 80 ]]; then
echo %{F$CYN}%{R}  %{R} $temp %{F-}
else
echo %{F$RED}%{R}  %{R} $temp %{F-}
fi
}

function life() {
bat=$(cat /sys/class/power_supply/BAT1/capacity)
echo %{F$GRN}%{R}  %{R} $bat %{F-}
}

function clock() {
time=$(date "+%a %d %b %R")
echo %{F$MAG}%{R}  %{R} $time %{F-}
}

echo "$(desk)$(music)%{r}$(temperature)$(life)$(clock) "
}
while :; do
echo $(statusbar)
sleep 0.1
done | lemonbar -f ${FONT} -g ${RES} -B ${FG} -F ${BG} &

