#!/bin/bash

BATTINFO=`acpi -b`
if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 02:00:00 ]] ; then
    DISPLAY=:0.0 /usr/bin/notify-send "Your Battery Sucks, Kemosabe" "$BATTINFO"
fi
